# Generated by Django 5.0.1 on 2024-01-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Discount_Deal',
            field=models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arrivals', 'New Arrivals')], max_length=100),
        ),
    ]
