# Generated by Django 5.0.1 on 2024-01-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_main_category_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
