# Generated by Django 5.0.1 on 2024-01-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
