# Generated by Django 5.0.1 on 2024-01-22 14:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_section_product_additional_information_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='media/product_img'),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='Image_url',
            field=models.ImageField(upload_to='media/product_img'),
        ),
    ]
