# Generated by Django 5.0.1 on 2024-01-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_slug_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
