# Generated by Django 5.0.1 on 2024-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_username_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Username_password',
        ),
    ]
