# Generated by Django 5.0.1 on 2024-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_slug',
            field=models.SlugField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
