# Generated by Django 5.0.1 on 2024-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_search_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_slug',
        ),
        migrations.AddField(
            model_name='product',
            name='search_tag',
            field=models.CharField(blank=True, max_length=500, verbose_name=models.CharField(max_length=500)),
        ),
    ]
