# Generated by Django 5.0.1 on 2024-01-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_product_search_slug_product_search_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_tag',
        ),
    ]
