# Generated by Django 5.0.1 on 2024-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_product_search_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Tags',
            field=models.CharField(max_length=1000),
        ),
    ]
