# Generated by Django 5.0.1 on 2024-03-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_coupon_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_Code',
        ),
    ]
