# Generated by Django 5.0.1 on 2024-03-13 06:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_coupon_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('addition_info', models.TextField(blank=True)),
                ('amount', models.IntegerField(default='')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime.today)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
            ],
        ),
    ]
