# Generated by Django 5.0.1 on 2024-03-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_orders_paid_orders_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='zip',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/orderitem'),
        ),
        migrations.AddField(
            model_name='orders',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
