# Generated by Django 5.0.1 on 2024-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_orders_zip_orderitem_image_orders_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
