# Generated by Django 5.0.1 on 2024-03-13 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_orderitem_ordersitem_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='PayableAmount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2024, 3, 13, 19, 59, 21, 193076)),
        ),
        migrations.AlterField(
            model_name='ordersitem',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
