# Generated by Django 5.0.1 on 2024-03-13 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_orders_payableamount_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersitem',
            old_name='order',
            new_name='orders',
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2024, 3, 13, 20, 1, 28, 333510)),
        ),
    ]
