# Generated by Django 5.0.1 on 2024-03-13 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_rename_order_ordersitem_orders_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 13, 21, 20, 6, 905285), null=True),
        ),
        migrations.AlterField(
            model_name='ordersitem',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
    ]
